//index.js
Page({
    data:{
        array:["张三","李四","王五","赵六"],
        object:{
            "姓名":"张三",
            "学号":"195612",
            "性别":"男"
        }
    },
    scoreInput:function(e){
        this.setData({
            score:e.detail.value
        })
    }
})